In [2]:
import pandas as pd

In [3]:
df_adaptive_exam_dataset_mcq = pd.read_csv('mixed_subjects_questions_dataset.csv')

In [4]:
df_adaptive_exam_dataset_mcq.duplicated().sum()

np.int64(32364)

In [5]:
df_adaptive_exam_dataset_mcq

,Subject,Question,Option_A,Option_B,Option_C,Option_D,Correct_Answer,Difficulty,Source,Tag,Q_ID,Year
0,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
1,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
2,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
3,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
4,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
...,...,...,...,...,...,...,...,...,...,...,...,...
37359,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37360,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37361,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37362,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37363,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009

In [6]:
df_adaptive_exam_dataset_mcq_cleaned = df_adaptive_exam_dataset_mcq.dropna(subset=["Question", "Correct_Answer"]).copy()
df_adaptive_exam_dataset_mcq_cleaned

,Subject,Question,Option_A,Option_B,Option_C,Option_D,Correct_Answer,Difficulty,Source,Tag,Q_ID,Year
0,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
1,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
2,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
3,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
4,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
...,...,...,...,...,...,...,...,...,...,...,...,...
37359,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37360,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37361,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37362,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009
37363,Economics,Which continent is the Sahara Desert located in?,Africa,Australia,Asia,South America,A,Hard,Notes,MCQ,5000,2009

In [7]:
df_adaptive_exam_dataset_mcq_cleaned['Question'].duplicated().sum()

np.int64(37036)

In [8]:
df_adaptive_exam_dataset_mcq_cleaned.loc[:, "Year"] = df_adaptive_exam_dataset_mcq_cleaned["Year"].astype(int)

In [9]:
df_adaptive_exam_dataset_mcq_cleaned = df_adaptive_exam_dataset_mcq_cleaned.drop_duplicates(subset=["Question"])

In [10]:
df_adaptive_exam_dataset_mcq_cleaned.loc[:, 'Correct_Answer'] = df_adaptive_exam_dataset_mcq_cleaned["Correct_Answer"].astype(str).str.strip().str.upper()

In [11]:
df_adaptive_exam_dataset_mcq_cleaned

,Subject,Question,Option_A,Option_B,Option_C,Option_D,Correct_Answer,Difficulty,Source,Tag,Q_ID,Year
0,Biology,What is the tallest mountain in the world?,Kilimanjaro,Denali,K2,Everest,D,Easy,Notes,MCQ,1,2011
6,Politics,Who painted the Mona Lisa?,Vincent Van Gogh,Michelangelo,Leonardo da Vinci,Pablo Picasso,C,Hard,Lecture,MCQ,2,2019
24,Computer Science,What does RAM stand for?,Random Access Memory,Read Access Memory,Real Allocation Memory,Rapid Access Memory,A,Hard,Website,MCQ,4,2015
37,Technology,Who was the first man on the moon?,Neil Armstrong,Buzz Aldrin,Michael Collins,Yuri Gagarin,A,Medium,Website,MCQ,6,2022
73,Chemistry,Which continent is the Sahara Desert located in?,Africa,Asia,South America,Australia,A,Medium,Book,MCQ,11,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
37113,Mathematics,What is 22 + 29?,53,52,50,51,D,Medium,Notes,MCQ,4968,2018
37130,Mathematics,What is 22 + 8?,29,32,31,30,D,Easy,Notes,MCQ,4970,2003
37305,Mathematics,What is 3 + 33?,35,38,36,37,C,Hard,Journal,MCQ,4992,2004
37324,Mathematics,What is 46 + 49?,95,97,96,94,A,Easy,Journal,MCQ,4995,2014
37351,Mathematics,What is 26 + 36?,61,63,64,62,D,Hard,Lecture,MCQ,4999,2013

In [12]:
print(df_adaptive_exam_dataset_mcq.shape)
print(df_adaptive_exam_dataset_mcq_cleaned.shape)

(37364, 12)
(328, 12)

In [35]:
columns = ["Subject", "Question", "Option_A", "Option_B", 
    "Option_C", "Option_D", "Difficulty", "Source", "Tag"]

df_adaptive_exam_dataset_mcq_cleaned[columns] = df_adaptive_exam_dataset_mcq_cleaned[columns].apply(lambda x: x.str.strip())

C:\Users\rusir.DESKTOP-KQL31O4\AppData\Local\Temp\ipykernel_16060\1427389902.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adaptive_exam_dataset_mcq_cleaned[columns] = df_adaptive_exam_dataset_mcq_cleaned[columns].apply(lambda x: x.str.strip())

In [49]:
df_adaptive_exam_dataset_mcq_cleaned.head()

,Subject,Question,Option_A,Option_B,Option_C,Option_D,Correct_Answer,Difficulty,Source,Tag,Q_ID,Year
0,Science,What planet is known as the Red Planet?,5,Mars,None of the above,Hydrogen,B,Easy,Unknown,MCQ,633,2020.0
1,Geography,What is the longest river in the world?,Nile,5,Russia,Silver,A,Hard,Notes,MCQ,268,2023.0
2,Economics,What is GDP?,Venus,Jupiter,Asia,Gross Domestic Product,D,Medium,Website,MCQ,520,2020.0
3,Economics,What is inflation?,None of the above,Africa,Adam Smith,Increase in general price levels,D,Easy,Unknown,MCQ,733,2024.0
4,Science,What is H2O commonly known as?,Unknown,Earth,Venus,Pacific Ocean,A,Easy,Book,MCQ,444,2021.0

In [39]:
df_adaptive_exam_dataset_mcq = df_adaptive_exam_dataset_mcq.drop_duplicates()

In [47]:
df_adaptive_exam_dataset_mcq['Question'].duplicated().sum()

np.int64(10765)

In [62]:
df_adaptive_exam_dataset_mcq.drop_duplicates(subset=["Question"], inplace=True)

C:\Users\rusir.DESKTOP-KQL31O4\AppData\Local\Temp\ipykernel_16060\2709546366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adaptive_exam_dataset_mcq.drop_duplicates(subset=["Question"], inplace=True)

In [63]:
df_adaptive_exam_dataset_mcq

,Subject,Question,Option_A,Option_B,Option_C,Option_D,Correct_Answer,Difficulty,Source,Tag,Q_ID,Year
0,Science,What planet is known as the Red Planet?,5,Mars,None of the above,Hydrogen,B,Easy,NaN,MCQ,633,2020.0
1,Geography,What is the longest river in the world?,Nile,5,Russia,Silver,A,Hard,Notes,MCQ,268,2023.0
2,Economics,What is GDP?,Venus,Jupiter,Asia,Gross Domestic Product,D,Medium,Website,MCQ,520,2020.0
3,Economics,What is inflation?,None of the above,Africa,Adam Smith,Increase in general price levels,D,Easy,NaN,MCQ,733,2024.0
4,Science,What is H2O commonly known as?,NaN,Earth,Venus,Pacific Ocean,A,Easy,Book,MCQ,444,2021.0
7,Mathematics,What is 2 + 2?,Earth,4,Hydrogen,London,B,Medium,Lecture,MCQ,927,2024.0
8,History,Who was the first President of the USA?,Tokyo,Rome,George Washington,Africa,C,Medium,Book,MCQ,547,2020.0
10,Computer Science,What does HTML stand for?,London,Silver,HyperText Markup Language,Atlantic Ocean,C,Easy,Journal,MCQ,477,2021.0
15,History,In which year did World War II end?,1945,Hydrogen,India,Atlantic Ocean,A,Easy,Notes,MCQ,215,2023.0
16,General Knowledge,What is the capital of France?,Karl Marx,Paris,22,Atlantic Ocean,B,Hard,Lecture,MCQ,216,2021.0
19,General Knowledge,Which is the largest ocean on Earth?,Pacific Ocean,Adam Smith,Pacific Ocean,Africa,A,Medium,Website,MCQ,967,2024.0
22,Computer Science,What does CPU stand for?,Earth,Central Processing Unit,Rome,Silver,B,Hard,Notes,MCQ,852,2024.0
23,Mathematics,Solve for x: 2x + 3 = 7,2,Adam Smith,3,Karl Marx,A,Medium,Lecture,MCQ,66,2021.0
33,Geography,Which country has the largest population?,None of the above,Rome,China,5,C,Hard,Lecture,MCQ,681,2022.0
43,Mathematics,NaN,Africa,Pacific Ocean,Venus,2,D,Easy,NaN,MCQ,894,2021.0